### ISSUE TITLE
Python not in image?

### ISSUE THREAD

**Issue by njbmartin** [CircleCI-Public/cimg-node#108]
Just updated one of my projects to use the `circleci/node@4.1.0` Orb. Doing so has resulted in my build failing due to `python` not found. I was previously using `circleci/node:lts`

![image](https://user-images.githubusercontent.com/5699471/97003903-1c2b1400-1534-11eb-99c0-467434098f1c.png)

Is there a reason for the difference between the two images and why python is not included as a core dev tool?

**Comment by felicianotech** [comment]
Python is not available in the Node.js image but is in the Python image (`cimg/python`). If you want both, you can use an orb to install one or the other but the fastest way is to use the Node variant of the Python image. This will give you a specified Python version and the LTS Node.js version at the time. For example, `cimg/python:3.8.0-node`.

I hope that helps.

**Comment by stephenh** [comment]
@felicianotech would be great to have a python variant of node, i.e. `cimg/node:16.0.0-python` :-)

(Specifically our build uses `aws` CLI to upload our artifacts to S3, so we can't move off `circleci/node` w/o having python; in general this seems like it'd be a common requirement, given the popularity of AWS/aws-cli.)

(Also, you mentioned using an orb to install python, but it looks like the primary python orb assumes you're using `cimg/python` and doesn't actually have an "install job" task: https://circleci.com/developer/orbs/orb/circleci/python)
