### ISSUE TITLE
Yarn global bin directory not in path

### ISSUE THREAD

**Issue by tallpants** [CircleCI-Public/cimg-node#142]
If you install  a package with `yarn global install`, it won't currently be available to use in subsequent commands, since Yarn's global binary path isn't in the bash path.

Since Yarn is pre-installed in this image, it makes sense to also add the global binary path to the environment that's used by the commands.

**Comment by felicianotech** [comment]
Confirmed & I agree.

**Comment by felicianotech** [comment]
Hey @tallpants, your suggestion has been implement. This change is already present in the Node.js v16.0.0 image that came out today. Any future Node.js tags released by us will include this change going forward.

**Comment by tallpants** [comment]
Awesome
