### ISSUE TITLE
Mutable tag request :stable

### ISSUE THREAD

**Issue by excenter** [CircleCI-Public/cimg-node#16]
`:<node-version>-stable`
is great if I want to lock to a specific version of node, but I'd really like to auto-select the stable version and revision of node a la `nvm install stable` 
THX

**Comment by iynere** [comment]
@excenter i'd recommend using our node orb, it will automatically install the latest stable release:

https://circleci.com/orbs/registry/orb/circleci/node#commands-install-node

i think our goal with these images is to be very explicit about versioning

that said, it's also worth noting that all of our other images' `-node` variants use `n` as a Node version manager, so you might try using `cimg/base:stable-node`, which use `n` to install the latest LTS release of Node by default (& then you can use `n` to switch to any other Node version at runtime, if you so desire):

https://github.com/circleci-public/cimg-base#stable-stable-node

**Comment by felicianotech** [comment]
This image will have aliases shortly. It won't be "stable" however.

Following how Node.js refers to their own release on their websites, there will be two aliases available. "current" and "lts".
