### ISSUE TITLE
Browser images without browsers

### ISSUE THREAD

**Issue by marpme** [CircleCI-Public/cimg-node#186]
#### Summary:
As referenced in this code snippet there are browser images for NodeJS that are shipped with the full set of dependencies of common browsers (i.e. firefox and chrome), but they never actually install the browser binaries.

https://github.com/CircleCI-Public/cimg-node/blob/a2864c1cd1c8063b78cf1b924431dffcfae7e229/16.3/browsers/Dockerfile#L28-L54

#### Actual behaviour:

* `google-chrome --version` is not a binary/executable
* `firefox --version` is not a binary/executable

#### Expected behaviour 

* `google-chrome --version` is returning the latest version of chrome
* `firefox --version` is returning the latest version of firefox

#### Technical insights:

Coming from `circleci/node`, there were actual browser binaries being shipped: https://github.com/CircleCI-Public/circleci-dockerfiles/blob/master/node/images/15.9.0-buster/browsers/Dockerfile

**Comment by marpme** [comment]
Oh I think I just saw that this is expected as you should choose yourself the version of the browser you want to install via the provided [browser-tool orb](https://circleci.com/developer/orbs/orb/circleci/browser-tools)!

**Comment by karlbrown-va** [comment]
What if we aren't using these images with CircleCI?
