### ISSUE TITLE
Global packages require sudo to install

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/cimg-node#214]
Node appears to be not configured after installation and mishandles global npm packages. 
https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

Installing Node via NVM would automatically configure pathing for global packages, or additional steps can be taken to create the global package path.

This issue was reported originally by the salesforce orb here: https://github.com/CircleCI-Public/Salesforce-sfdx-cli-orb/issues/17

`sudo` would work to install the packages but by NPM's own documentation this is not advised.

The Node Orb's install command should be unaffected as it assumes you are using NVM and will install it if not present.

**Comment by JalexChen** [comment]
Closed with #218
