### ISSUE TITLE
node:current - /bin/bash: line 6: npm: command not found

### ISSUE THREAD

**Issue by villelahdenvuo** [CircleCI-Public/cimg-node#241]
Getting npm command not found error when trying the latest tag 18.1

**Comment by JalexChen** [comment]
the fix was just merged in #240 - i would suggest giving a couple minutes for the new builds to be built and pushed to dockerhub

**Comment by jameskip** [comment]
@JalexChen We are still seeing this issue with `14.19.2`. Any suggestions?

<img width="308" alt="Screen Shot 2022-05-11 at 11 59 53 AM" src="https://user-images.githubusercontent.com/16872140/167906037-8b7584d3-f25c-4f5f-b918-fbce81c23029.png">
 
Thanks

**Comment by JalexChen** [comment]
hi @jameskip - with some of the changes that were made this morning, the symlink that existed is gone while we try to figure out a more reliable way of implementing this. A stopgap solution could be to try running the following lines, which links nvm to root. However, if you end up changing the version of node or npm with nvm, you may need to run this link again. as the $(nvm version) may have changed.

`sudo ln -sf $NVM_DIR/versions/node/$(nvm version)/bin/node /usr/local/bin/node`
`sudo ln -sf $NVM_DIR/versions/node/$(nvm version)/bin/npm /usr/local/bin/npm`

**Comment by jameskip** [comment]
Thank you @JalexChen. This has has fixed our issue. Is there a way to link multiple node and npm versions if we have workflows that use separate node versions?

**Comment by jprice-da15252** [comment]
I was able to resolve it for my teams just by avoiding the use of `sudo` altogether.

Example replacement: 
```
sudo npm i -g <dep>
```
to 
```
npm i -g <dep>
```
