### ISSUE TITLE
Recent image broke `npm --prefix DIR run` functionality

### ISSUE THREAD

**Issue by korya** [CircleCI-Public/cimg-node#248]
Sometime on May 11, 2022, `cimg/node:lts-browsers` was updated and our current setup got broken. The details are:
- the latest "good" image is
`cimg/node@sha256:c8ea4df07599f2c676c81f6dfecb22237da28428997589b28e8afa0afee8e96f`
- the current "bad" image is `cimg/node@sha256:c74edbc4f04bab52e47ca8a77e5a44cfb6241a13a87687262e554a345ac5359d`

The minimum project demonstrating the problem is available at https://github.com/korya/circleci-node-issue. 

Below are the steps to reproduce the problem using https://github.com/korya/circleci-node-issue.

### Good old image

```sh
docker run -ti --rm -v `pwd`:/home/circleci/project cimg/node@sha256:c8ea4df07599f2c676c81f6dfecb22237da28428997589b28e8afa0afee8e96f
# Inside the image
bash
npm i
npm run test
# Result: the command succeeds and outputs `SUCCESS!`
```

Overall output should be as follows:

```sh
 $ docker run -ti --rm -v `pwd`:/home/circleci/project cimg/node@sha256:c8ea4df07599f2c676c81f6dfecb22237da28428997589b28e8afa0afee8e96f
$ _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

$ bash
circleci@cea7ca1f3f90:~/project$ npm i

up to date, audited 3 packages in 454ms

found 0 vulnerabilities
circleci@cea7ca1f3f90:~/project$ npm run test

> @korya/min-circleci-setup@1.0.0 test
> npm --prefix packages/sub-project test


> @korya/sub-project@1.0.0 test
> ./test.sh

v16.15.0
SUCCESS!
npm notice
npm notice New minor version of npm available! 8.5.5 -> 8.10.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.10.0
npm notice Run npm install -g npm@8.10.0 to update!
npm notice
npm notice
npm notice New minor version of npm available! 8.5.5 -> 8.10.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.10.0
npm notice Run npm install -g npm@8.10.0 to update!
npm notice
```

### Bad new image

```sh
docker run -ti --rm -v `pwd`:/home/circleci/project cimg/node@sha256:c74edbc4f04bab52e47ca8a77e5a44cfb6241a13a87687262e554a345ac5359d
# Inside the image
bash
npm i
npm run test
# Expected result: the command succeeds and outputs `SUCCESS!`
# Actual result: the command fails with
#     /usr/bin/env: ‘node’: No such file or directory
```

Overall output I get is:

```sh
$ docker run -ti --rm -v `pwd`:/home/circleci/project cimg/node@sha256:c74edbc4f04bab52e47ca8a77e5a44cfb6241a13a87687262e554a345ac5359d
$ _XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
bash
circleci@406d4bbc3b6c:~/project$ npm i

up to date, audited 3 packages in 467ms

found 0 vulnerabilities
circleci@406d4bbc3b6c:~/project$ npm run test

> @korya/min-circleci-setup@1.0.0 test
> npm --prefix packages/sub-project test


> @korya/sub-project@1.0.0 test
> ./test.sh

nvm is not compatible with the "npm_config_prefix" environment variable: currently set to "/home/circleci/project/packages/sub-project"
Run `unset npm_config_prefix` to unset it.
./test.sh: line 5: node: command not found
/usr/bin/env: ‘node’: No such file or directory
npm notice
npm notice New minor version of npm available! 8.5.5 -> 8.10.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v8.10.0
npm notice Run npm install -g npm@8.10.0 to update!
npm notice
```

### Latest image

At this moment, 2022-05-12 08:00 ET, the latest `cimg/node@lts-browsers` is
broken.

```sh
docker run -ti --rm -v `pwd`:/home/circleci/project cimg/node:lts-browsers
# Inside the image
bash
npm i
npm run test
# Expected result: the command succeeds and outputs `SUCCESS!`
# Actual result: the command fails with
#     /usr/bin/env: ‘node’: No such file or directory
```

**Comment by JalexChen** [comment]
Hi @korya - I'm noticing you are using the lts tag. we just built and pushed up new images with the fixes from yesterday. Could you please check if you are still being affected?

**Comment by korya** [comment]
Yes, same issue: https://app.circleci.com/pipelines/github/korya/circleci-node-issue/1/workflows/f7721791-349e-4ef2-a14a-65fcf40444ec/jobs/1

**Comment by JalexChen** [comment]
Hi @korya, from what i've discovered, the good image that you're referencing is an image that i built and was creating a symlink from where nvm was to where node and npm would normally be. since then, that functionality has been changed and the symlink is no longer created, which is causing node to not be found where it normally is; specifically this command in the Dockerfile:

`sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node" && sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm"`

there are two solutions here (that i know of): 

1) `"$NVM_DIR/versions/node/v16.15.0/bin/npm --prefix packages/sub-project test"` would allow you to run things correctly, in the package.json test pair, however, this requires you to hard code the node version v16.15.0, which is fine if you are not switching between any versions of node

2) `cd packages/sub-project && chmod +x test.sh && npm run test` would also run the tests successfully regardless of image and could be implemented as a run step

**Comment by korya** [comment]
@JalexChen thanks for the update.

The second solution suggested by you is what we used to do in the past before we migrated to workspaces. We will use it until the issue is solved properly.

Do you have any idea what is the priority of this bug and when it is going to be fixed?

**Comment by markwhitfeld** [comment]
We are also having problems with this image.
I left a comment on the PR: https://github.com/CircleCI-Public/cimg-node/pull/237#issuecomment-1129324603
Wouldn't rolling back the nvm changes be the step to take in the interim?

**Comment by JalexChen** [comment]
Hey @korya - a couple of things here:

- --prefix is 1) not compatible with nvm (per the errors) 2) [is not aware of workspaces](https://docs.npmjs.com/cli/v8/commands/npm-prefix)
- instead using `"npm test --workspaces"` for your test key in package.json would execute correctly and you could add as many different workspaces within that key
- lastly, you could also replace --prefix and run `cd packages/sub-project && npm test`

let me know if this works for you

**Comment by korya** [comment]
Thanks for you response.

`--workspaces` will not work for us because we need to run a script in a specific package at a specific time. Will `npm run -w <DIR> <SCRIPT>` work with nvm?

The last options works but is less ideal because it requires us to significantly change our build scripts. We would like to avoid doing it because of a regression bug in a CI image.

**Comment by JalexChen** [comment]
Hi @korya,

yes, `npm run -w package/sub-project test` would work per the [workspaces docs](https://docs.npmjs.com/cli/v8/using-npm/workspaces)

**Comment by korya** [comment]
@JalexChen Thanks! The suggested approach works as expected.
