### ISSUE TITLE
symlink `npm`, `node` to /usr/loca/bin

### ISSUE THREAD

**Issue by ryuheechul** [CircleCI-Public/cimg-node#265]
[Currently `sudo npm` fails to find the path on 18.x images because of use of nvm](https://gist.github.com/ryuheechul/e4c1ba86fc602f2a643560e00f1f9871).

Symlink-ing like this, https://stackoverflow.com/questions/21215059/cant-use-nvm-from-root-or-sudo/40078875#40078875 resolves the issue, while users of the images can do this manually with extra steps, it would be nicer for this to be out of the box on upstream build stage.

**Comment by felicianotech** [comment]
@JalexChen Does this work for us or does it contradict the recent recommendation we had of not using `sudo`?

**Comment by ryuheechul** [comment]
use cases of symlinking to `/usr/local/bin` shouldn't be limited to `sudo` in my opinion. 
one example, entering with different shell than bash.

**Comment by ryuheechul** [comment]
@JalexChen thanks for your reply and explanation and here are my response to that.

> you shouldn't need to use sudo at all when using nvm

I agree that it's a good practice but the image shouldn't make the decision for users on that. Also some script might need `sudo` and `npm` at the same time and it might natural to call that script like below

```bash
$ cat <<EOF> script-that-needs-sudo.sh
command-that-fail-if-not-sudo
npm ...
node ...
EOF

# this will fail to find `node` and `npm`
$ sudo script-that-needs-sudo.sh
```

_Although the better version for it should be like below, there is no guarantee that every one write like this including potential third party or unfamiliar dependencies._
```bash
$ cat <<EOF> script-that-needs-sudo-only-for-certain-commands.sh
sudo command-that-fail-if-not-sudo
npm ...
node ...
EOF

$ script-that-needs-sudo-only-for-certain-commands.sh
```

> is there a specific reason you need this?

Yes. The specific reason for me: `node`, `npm` to be discoverable from any shell not just from bash, and even when there is no additional path is added to `$PATH`. Using `sudo` happen to fall in category.
_I personally avoid using `sudo` as much as possible, but that might not be the case for others in a team._

I think these reasons alone are good enough to justify enabling this capability:
- `node` and `npm` was under `/usr/local/bin/` from `17.*` images
- installing node in "regular" way result in binary discoverable under `/usr/local/bin/`
- [official node image](https://github.com/nodejs/docker-node/blob/main/18/bullseye-slim/Dockerfile) binaries are under `/usr/local/bin/` and it's reasonable for people to expect the similarity between the official node image and `cimg/node`
  > ```
  > $ docker run --rm -it node:18-slim bash
  > root@4afe58bcb460:/# which node
  > /usr/local/bin/node
  > root@4afe58bcb460:/# which npm
  > /usr/local/bin/npm
  > ```

Otherwise, people might just run commands like below (or whatever other hacks) themselves at some point in the CircleCI steps and feel that the image is "not that convenient".
```
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/node" "/usr/local/bin/node"
sudo ln -s "$NVM_DIR/versions/node/$(nvm version)/bin/npm" "/usr/local/bin/npm"
```

**Comment by JalexChen** [comment]
hey @ryuheechul - i think these are all valid and after deliberation, we've decided to move away from nvm, especially since the cimg's should still be deterministic and reflect one specific version of node. We'll be re-implementing this shortly and sudo functionality will point to the node and npm versions in /usr/local/bin

**Comment by ryuheechul** [comment]
Hi @JalexChen, sounds good to hear and moving away from `nvm` seems to be the right choice 👍🏼.
Thanks a lot for the update!
