### ISSUE TITLE
Latest release of node:lts-browsers breaks corepack prepare/activate

### ISSUE THREAD

**Issue by Codeneos** [CircleCI-Public/cimg-node#277]
After the latest release of the `cimg/node:lts-browsers` my circle-ci builds started failed due to lacking permissions on `/usr/local/bin` folder. 

I am using corepack to install and activate pnpm as package manager which used to work great but since the last release my builds are failing with the error below:

```shell
corepack enable && corepack prepare $(node -p "require('./package.json').packageManager") --activate
Internal Error: EACCES: permission denied, symlink '../lib/node_modules/corepack/dist/pnpm.js' -> '/usr/local/bin/pnpm'
Error: EACCES: permission denied, symlink '../lib/node_modules/corepack/dist/pnpm.js' -> '/usr/local/bin/pnpm'

Exited with code exit status 1
CircleCI received exit code 1
```
Specifically the command `corepack enable` fails. As this happens on all recent cimg/node releases it is probably a change in the base image. Either in the `ubuntu` image or in `cimg/base`.

This will also affect other tools that create symlinks in `/usr/local/bin`; a quick solution would be to grant write permission on `/usr/local/bin` but not sure if it makes sense to do that in [cimg-node](https://github.com/CircleCI-Public/cimg-node) or bring the issue to one of the upstream images that cimg-node is based on. 

Switching back to an older version of cimg-node resolves the issue: `cimg/node:16.6-browsers` or `cimg/node:18.4-browsers` 

* [Failing built](https://app.circleci.com/pipelines/github/Codeneos/vlocode/221/workflows/b5a915af-697d-493a-a5ab-ebb5b25b1979/jobs/266)
* [Successful built using the same image 2 days ago](https://app.circleci.com/pipelines/github/Codeneos/vlocode/219/workflows/23d0836d-883c-4198-a122-3c809a11579e/jobs/262)

**Comment by felicianotech** [comment]
Touching anything that the default user doesn't own (`circleci`), such as a path in the root filesystem requires root access. Prefixing with `sudo` should do the trick. A few older images didn't require this as we switched to `nvm` however due to several issues, we've switched back to using raw Node.js in the image.

Newer releases of the image, including the 18.8.0 release we're doing today, will include pnmp btw.

**Comment by Codeneos** [comment]
@felicianotech thanks for the tip! And good to know what caused the issue.

And its great to hear the new images will now include pnpm as standard 🎉

**Comment by brandonchinn178** [comment]
Just to be clear, usage of `cimg/node` is expected to run `sudo corepack enable`? Can that be added to the docs at all? Given that `corepack` is moving to be the official way of setting up package managers, it should be easy for devs to find this command

Note: this is a regression of #212
