### ISSUE TITLE
Latest version of image run out of memory

### ISSUE THREAD

**Issue by korya** [CircleCI-Public/cimg-node#278]
The latest versions of `cimg/node:lts-browsers` are running out of memory.

Our CI job is the same and does not change but:
- `cimg/node@sha256:5f2070d5e582a32f977e14e8d7e611acf91e4affb10dc4cf9e536e040dfd7038` runs out of memory and fails
- `cimg/node@sha256:542f4764aa5e3dd7e9372ac3ede108639cf95bc752b5065ce0d3f8941a10834e` works as expected and the job succeeds

The failing job is https://app.circleci.com/pipelines/github/PlanitarInc/walk-inside-app/6599/workflows/7b50389c-d6e8-4041-8683-5ab876f620d8/jobs/42888/steps

Please let me know if you need more details.

**Comment by felicianotech** [comment]
The only thing changed between images (at the time) was the version of Node.js ( [ref](https://github.com/CircleCI-Public/cimg-node/pull/275/files) ).

Perhaps memory usage in Node.js has increased? If so, hopefully a future release might be able to lower it. Or, you'll want to use a resource class with more RAM. https://circleci.com/product/features/resource-classes/

**Comment by BytesGuy** [comment]
@korya I am going to close this issue out as we have not heard back from you for a while. The PR @felicianotech linked to just appear to just be a version bump, so this is likely a node issue, or your jobs may have previously been on the borderline of running out of memory. If this is still a problem feel free to re-open the issue!
