### ISSUE TITLE
Using the image in other CI tools 

### ISSUE THREAD

**Issue by kkattamudi** [CircleCI-Public/cimg-node#283]
Hi Team , 

Can we use this image with other CI tools like GitHub actions or Jenkins and expect to work the same ?

**Comment by ttomaszewski** [comment]
Wondering the same. Tried using in Jenkins but the container never started and hung up.

**Comment by kkattamudi** [comment]
> Wondering the same. Tried using in Jenkins but the container never started and hung up.

I have tried using in GitHub actions but it did not worked as expected.

**Comment by JalexChen** [comment]
These images are configured specifically for the CircleCI environment and is not guaranteed to work if at all on other CI tools. If there is any feedback on what you might want to include, we would be happy to take a look and consider inclusion
