### ISSUE TITLE
shallow checkout

### ISSUE THREAD

**Issue by joshribakoff-sm** [CircleCI-Public/cimg-node#285]
Any reason not to do a shallow checkout? https://support.circleci.com/hc/en-us/articles/360045096514-Shallow-Repository-Cloning

**Comment by felicianotech** [comment]
In what context? For what?

**Comment by joshribakoff-sm** [comment]
The link I posted outlines how you would do a shallow checkout, and why:

> Shallow cloning a git repository can offer some performance improvement, especially for larger projects with a number of commits, by pulling the smallest number of changes possible. This can either be implemented manually using a custom cloning step or by utilizing [an Orb](https://circleci.com/orbs/registry/?filterBy=all&query=shallow).

**Comment by felicianotech** [comment]
If you're talking about the example config in this repository's readme, it is showing the CircleCI `checkout` step. The step doesn't always do a full clone, it depends on the scenario. Regardless, it's the default way to checkout code on CircleCI which works for most people, this is why it's used in the example.

Thank you for the suggestion.

**Comment by joshribakoff-sm** [comment]
I assumed this orb was providing that step, but if not apologies for filing on the wrong repo

**Comment by felicianotech** [comment]
This repository is for the Node.js Convenience Image. If you're looking for the Node.js Orb, that can be found here: https://github.com/CircleCI-Public/node-orb

I hope that helps. 🙂
