### ISSUE TITLE
cimg/node:16.18 & cimg/node:16.19: "Mongod instance closed with code \"127\"" was thrown, throw an Error :)

### ISSUE THREAD

**Issue by canadaleks** [CircleCI-Public/cimg-node#314]
Startring with the 16.18.0 node docker image, we have been seeing failures in our tests running through CircleCI.  THe issue is only present when running our tests in the following images:

- cimg/node:16.18.0
- cimg/node:16.19.0

cimg/node:16.17.0 works just fine.

The issue looks to be around our tests that are testing mongodb things:

```txt
1) TableService
       "before all" hook in "TableService":
     Error: the string "Mongod instance closed with code \"127\"" was thrown, throw an Error :)
      at thrown2Error (/home/circleci/project/Ready.Table/node_modules/mocha/lib/runner.js:1241:10)
      at Runner.fail (/home/circleci/project/Ready.Table/node_modules/mocha/lib/runner.js:443:11)
      at cbHookRun (/home/circleci/project/Ready.Table/node_modules/mocha/lib/runner.js:532:14)
      at done (/home/circleci/project/Ready.Table/node_modules/mocha/lib/runnable.js:310:5)
      at /home/circleci/project/Ready.Table/node_modules/mocha/lib/runnable.js:377:11
```

Running our tests on local machines using node 16.18 and 16.19 work just fine.

**Comment by BytesGuy** [comment]
@canadaleks Without seeing a full job this is going to be hard to diagnose. 

I am not sure this is directly related to this node image as mongo itself is crashing, not node. If I had to guess, it would seem more related to memory/resource issues in your job causing mongo to crash. 

`16.18` uses a newer base image than `16.17`, so it is entirely possible that slightly more memory is in use in the newer image and thus causing mongo to crash as it does not have enough resources.

Are you running mongo in the same docker container, or as a separate service container? Either way, I would suggest trying to bump your resource class up a notch to see if this helps.

**Comment by BytesGuy** [comment]
@canadaleks As we have not heard back from you for a while I will go ahead and close this issue. If you are still facing issues please feel free to reopen this issue in the future. Thanks!
