### ISSUE TITLE
Feature Request: Update open JDK to the next LTS

### ISSUE THREAD

**Issue by rvdkraan** [CircleCI-Public/cimg-node#352]
**Describe the Feature Request**
Please update the Open JDK for Java to the next LTS version. The current one is about to be depricated. 

**Is your feature request related to a particular problem?**
Our workflow gives a warning the the current Java version is soon to be depricated. 

**How will this feature request benefit CircleCI jobs using this image?**
To be able to use this cimg the java version needs to be updated or we need to create a custum image. 

**Describe the solution you would like to see**
update open JDK to version 17 

**Describe alternatives you have considered**
none

**Comment by TheMetalCode** [comment]
I don't think `cimg/node` has java installed to begin with.

```bash
➜  ~ docker run -i -t cimg/node:current bash
circleci@42f7843c3f8a:~/project$ java --version
bash: java: command not found
circleci@42f7843c3f8a:~/project$ which java
circleci@42f7843c3f8a:~/project$ echo $JAVA_HOME

```

See also https://github.com/CircleCI-Public/cimg-node/blob/main/20.5/Dockerfile#L9

You may wish to provide more detail about which _part_ of your workflow is throwing warnings about java version. In my case, it was Sonarcloud scans and upgrading to v5 of the sonar-scanner-cli (which is build with java 17 instead of 11) resolved the warning.

**Comment by rvdkraan** [comment]
Hi Jason

You are correct.
I was wondering how Java ended up in the image.
The sonar scanner uses an embedded version of java.

In my case I use the scanner from npm which is in progress to be updated to java 17.
https://community.sonarsource.com/t/java-11-is-deprecated-as-a-runtime-env-to-scan-your-projects/96597

Thanks for your help.

**Comment by BytesGuy** [comment]
Hi, I can confirm Java is not included in this image, therefore I am closing this issue. Thanks!

**Comment by nielsvaneck** [comment]
the `-browsers` versions of these images include [java 11](https://github.com/CircleCI-Public/cimg-node/blob/main/variants/browsers.Dockerfile.template#L25)
