### ISSUE TITLE
Bug Report: wrong LTS version

### ISSUE THREAD

**Issue by borisyordanov** [CircleCI-Public/cimg-node#370]
*Note: We also welcome PRs to fix bugs! This helps us take action faster where a bug has been identified!*

For our official CircleCI Docker Convenience Image support policy, please see [CircleCI docs](https://circleci.com/docs/convenience-images-support-policy).

This policy outlines the release, update, and deprecation policy for CircleCI Docker Convenience Images.

---

**Describe the bug**
Incorrect Node version installed which causes conflicts with package engines
```
npm ERR! notsup Required: {"npm":">=10.0.0","node":">=20.9.0"}
npm ERR! notsup Actual:   {"npm":"9.8.1","node":"v18.18.0"}
```

**To Reproduce**
Create a job that uses an lts image
```
  deploy:
    resource_class: large
    docker:
      - image: cimg/node:lts 
 ```

**Expected behavior**
The image should contain the current LTS version of node - Node.js 20.9.0 and 10.1.0
https://nodejs.org/en
https://nodejs.org/en/download/releases#looking-for-latest-release-of-a-version-branch

**Workarounds**
None - The correct version can be hardcoded in the image with `cimg/node:20.9.0`, but this image is not available at https://github.com/CircleCI-Public/cimg-node/tree/main/20.9

**Screenshots and Build Links**

https://docs.npmjs.com/cli/v10/configuring-npm/package-json#engines

**Additional context**
The LTS version change announcement happened 2 days ago - https://nodejs.org/en/blog/release/v20.9.0

**Comment by HugoDiFrancesco** [comment]
I found it interesting that the ALIASES file has the correct version https://github.com/CircleCI-Public/cimg-node/blob/0163b7d25bb94daae8ef820c679d53f3c64c7d79/ALIASES#L2

I'm wondering if the CI/publish for this commit (https://github.com/CircleCI-Public/cimg-node/commit/0163b7d25bb94daae8ef820c679d53f3c64c7d79) didn't actually run correctly?

**Comment by HugoDiFrancesco** [comment]
One of my colleagues got in touch with CircleCI support and `lts` is now using Node 20, `current` is now using Node 21

**Comment by JalexChen** [comment]
hey guys - thanks for bringing this up. Yes, #371 is intended to fix this as we stopped running the script. However, the `lts` and `current` tags should be referencing the correct versions now. Please reopen if you run into additional issues.
