### ISSUE TITLE
Feature Request: February Node security releases

### ISSUE THREAD

**Issue by lizthegrey** [CircleCI-Public/cimg-node#387]
**Describe the Feature Request**
https://nodejs.org/en/blog/vulnerability/february-2024-security-releases/

**Is your feature request related to a particular problem?**
**How will this feature request benefit CircleCI jobs using this image?**
CircleCI users cannot build with the latest up to date secure node.

**Describe the solution you would like to see**
Add Node 21.6.2, 20.11.1, and 18.19.1

**Describe alternatives you have considered**
n/a

**Comment by rickharrison** [comment]
Yes please, I'd also love 20.11.1

**Comment by lizthegrey** [comment]
https://github.com/CircleCI-Public/cimg-node/pull/388 is in progress it looks.

**Comment by schinery** [comment]
I've created https://github.com/CircleCI-Public/cimg-node/pull/389 to replace https://github.com/CircleCI-Public/cimg-node/pull/388 which has all 3 images.

**Comment by lizthegrey** [comment]
Closed by #391
