### ISSUE TITLE
cannot instal aws-s3 orb

### ISSUE THREAD

**Issue by xavar87** [CircleCI-Public/cimg-node#65]
/usr/bin/env: ‘python’: No such file or directory

**Comment by felicianotech** [comment]
Hi,

You need to install Python, or use an image that contains Python. This repository is for the Node.js image that contains Node.js, not Python.

I'd suggest using the Python image (`cimg/python`). If you also need Node.js, there's a Node variant for the Python image. https://github.com/CircleCI-Public/cimg-python

**Comment by xavar87** [comment]
Ok, 
so I understand that I cannot build node app and publish it to s3 or lambda using only one image? 
In old image (circleci/node) it was possible.

**Comment by felicianotech** [comment]
You can. Please see the link I provided in my previous comment.

**Comment by yliu-d** [comment]
We have a similar issue but in our case we need to build both go application, nodejs application and nodejs native addon (during yarn install, and the build process requires python). There is no image that contains all of these tools. Can we add python to all the node variant so that `yarn install` always work?

**Comment by felicianotech** [comment]
We won't be adding Python to the `-node` variant.

A fast option is to build your own custom image, but I know not everyone wants to do that. So my suggestion would be to use the Python image, but the `-node` variant. This gives you two of the three languages pre-installed. Then use the [Go orb](https://github.com/CircleCI-Public/go-orb) to install Go on the fly, which is fairly fast. Then you'll have all three languages installed.
