### ISSUE TITLE
-ubuntu and -browsers extensions

### ISSUE THREAD

**Issue by Ruluk** [CircleCI-Public/cimg-node#77]
Hey there!

I want to know whether there are any plans to add support for these label extensions to directly declare them in an executor. They exist in the current-gen images.

**Example**

`cimg/node:10.20-buster-browsers`

**Comment by Ruluk** [comment]
I just noticed that they are based on Ubuntu, not Debian. Would it make sense to add the Ubuntu version then?

**Example**

`cimg/node:10.20-bionic-browsers`

**Comment by felicianotech** [comment]
Just to close this out, `-browsers` is considered a variant image and is available as of early this year (or not late last year). It is used in conjunction with the [Browser Tools Orb](https://circleci.com/developer/orbs/orb/circleci/browser-tools).

The tag portion that includes an OS or OS codename is no longer a thing with next-gen Convenience Images. They are all Ubuntu based using the latest LTS release.
